// <auto-generated />
using System;
using KOF.Desafios.Infrastructure.Repositories.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KOF.Desafios.Infrastructure.Migrations
{
    [DbContext(typeof(AppDesafiosDbContext))]
    [Migration("20250711160020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KOF.Desafios.Domain.Entities.Desafios.InformacionGeneral", b =>
                {
                    b.Property<int>("IdDesafio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDesafio"));

                    b.Property<string>("DescripcionDesafio")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("FechaCancela")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdSegmentacion")
                        .HasColumnType("int");

                    b.Property<string>("JsonMateriales")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("LogotipoDesafio")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Promocion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PuntosExtra")
                        .HasColumnType("int");

                    b.Property<string>("TituloDesafio")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioCancela")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsuarioCierre")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsuarioPublicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdDesafio");

                    b.ToTable("InformacionGeneral", "desafio");
                });

            modelBuilder.Entity("KOF.Desafios.Domain.Entities.Desafios.InformacionParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdDesafio")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusDesafio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InformacionParticipante", "desafio");
                });
#pragma warning restore 612, 618
        }
    }
}
